import { Inter } from 'next/font/google';
import clsx from 'clsx';
import type { Metadata } from 'next';

import { Providers } from './providers';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={clsx(
          inter.className,
          'min-h-screen bg-background antialiased'
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
