name: Deploy reminder-mailer to Fly.io

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: .

      - name: Install NX
        run: npm install -g nx

      - name: Build Node App
        run: nx build reminder-mailer
        working-directory: .

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --app reminder-mailer --config fly.toml
        working-directory: apps/reminder-mailer
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
